### ISSUE TITLE
BUG REPORT: Function Hashes NOT WORKING

### ISSUE THREAD

**Issue by jjmr007** [ethereum/remix-desktop#185]
Hello guys,
Sorry abot this report, but didn't find any template on guidelines to report a bug. So here it is:

Reproduce the bug:
1.- Go to Chrome / Firefox Remix site (https://remix.ethereum.org/) and loas a solidity contract.
2.- Example of contract: https://explorer.rsk.co/address/0x37ff40ec727349d478d2715ae58097f218f7e03f?__ctab=Code
3.- Go to the solidity compiler button, and specify the desired settings. (E.G.: in this case: compiler = 0.6.12, EVM VERSION: instanbul, optimization runs (true): 200)
4.- Run compile.
5.- Look for ANY of the contracts compiled (E.G.: CoinPairPrice) and hit Compilation Details.
6.- A modal appears when you can select "FUNCTION HASHES" which is now always EMPTY.

Expected behavior: List all the external and public functions with their respective function hashes 
![REMIX_BUG](https://user-images.githubusercontent.com/17028457/221623422-e9cf61d4-56a2-43a6-b6f2-d5a28f27b99f.png)

**Comment by ryestew** [comment]
Thanks [jjmr007](https://github.com/jjmr007) for the bug report.  It is in fact very timely.  Tomorrow we should be releasing the next version of Remix which includes fixing this issue.  If you need this information in Function Hashes before tomorrow, go to https://remix-beta.ethereum.org - the fix is already there.
