### ISSUE TITLE
How to use a wallet and network? Can't access metamask like on the browser version.

### ISSUE THREAD

**Issue by dave-dm** [ethereum/remix-desktop#19]

**Comment by yann300** [comment]
The next release will bring a solution to this.

**Comment by yann300** [comment]
Hopefully next week

**Comment by yann300** [comment]
if you run it now, it should update to latest remix (0.10.5), this include a way to connect remix with a mobile wallet (e.g metamask mobile). You just need to activate the plugin `wallet connect` , we'll add some documentation soon.

**Comment by yann300** [comment]
now you should be able to use wallet connect (you then need a mobile wallet).

**Comment by bertho-zero** [comment]
A track to study: https://medium.com/swapynetwork/integrating-metamask-with-electron-a-simple-secure-and-non-intrusive-approach-517a04da1656

**Comment by bertho-zero** [comment]
The boilerplate: https://github.com/SwapyNetwork/electron-metamask-boilerplate

**Comment by Drjacky** [comment]
@yann300 But we need Infura ID (which after 100K requests is not free).

**Comment by yann300** [comment]
yes I know... are you reaching it easily? do you know if one can use another provider instead of infura (with wallet connect)
The things is that our key (which was then publicly available) was used for spamming, this is why we needed to ask you guys to provide your own infura key.. I regret that but don't see another solution yet

**Comment by frankzielen** [comment]
Even with my infura ID (free account) it doesn't work. Both iOS wallets, MetaMask and Coinbase, do not accept the QR code (MetaMask: nothing happens after scanning; Coinbase: message "Invalid QR code"). I have selected Ethereum mainnet and Kovan testnet in apps before scanning - same behaviour. Any ideas? And finally, even if it would work with infura ID - would I be able to connect my wallet for BSC Smart Chain?

**Comment by bunsenstraat** [comment]
Should be fine again.

**Comment by frankzielen** [comment]
Many thx. It's now possible to connect with MetaMask. When choosing Environment "Wallet Connect" the network selected in MetaMask is shown below, however, the address of the connected account is not shown in the Account data field (it's empty). So it's not possible to deploy a contract (Remix tries and fails to create a new owner - I believe this is because address field is empty).

**Comment by yann300** [comment]
did you unlock metamask? you have to do that before using one of its addresses.

**Comment by frankzielen** [comment]
The app isn't screen-locked - do you mean this? I can connect to Remix with MetaMask and Remix shows the account address in "Wallet Connect" tab however account field in DEPLOY & RUN TRANSACTIONS is empty.

**Comment by yann300** [comment]
In the `DEPLOY & RUN TRANSACTIONS` did you switch to the wallet connect provider?

**Comment by frankzielen** [comment]
Yes. Sometimes it's even not possible to switch to "Wallet Connect" (there's no change when clicking on the wallet connect entry in the environment dropdown). Then I need to disconnect MetaMask or to deactivate the whole wallet connect plugin to make it selectable again.
